### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by csf30816** [TheLukeGuy/thelukeguy.github.io#1]
Just informing you I think I fixed that bug, although I don't know. Could you test?

**Comment by TheLukeGuy** [comment]
Doesn't look like it's working...

**Comment by csf30816** [comment]
OK, just fixed it completely :P

**Comment by csf30816** [comment]
It will just take a while to update.

**Comment by TheLukeGuy** [comment]
Alright, thanks!

**Comment by TheLukeGuy** [comment]
How long do you think it will take to update?

**Comment by csf30816** [comment]
OK, if you have any other trouble just tell me. Operating hours Friday - Sunday 8:00AM - 8:00PM HST

**Comment by TheLukeGuy** [comment]
Alright!

**Comment by csf30816** [comment]
If the console still says `Uncaught TypeError: document.getElementsByTagName(...).addEventListener is not a function at window.onload (emoji.js:86)` then it has not updated.

**Comment by TheLukeGuy** [comment]
Alright, thank you!

**Comment by TheLukeGuy** [comment]
Still not working. Console has no errors. Here's a GIF of this: https://gfycat.com/CelebratedRemarkableBluejay

**Comment by csf30816** [comment]
OK, let me check this out...

**Comment by TheLukeGuy** [comment]
Alright

**Comment by csf30816** [comment]
Hmmm... I do not know what is wrong, sorry. I got to go now. I will be back.

**Comment by TheLukeGuy** [comment]
Alright, that's fine

**Comment by csf30816** [comment]
Think I found a solution.

**Comment by TheLukeGuy** [comment]
Awesome! Did you update the code yet?

**Comment by csf30816** [comment]
Need to check.

**Comment by csf30816** [comment]
No

**Comment by csf30816** [comment]
it updated, but does not work. Working on bug fix. Sorry for wait.

**Comment by csf30816** [comment]
FIXED IT!!!! Tell me if you need anything else!

**Comment by TheLukeGuy** [comment]
Awesome! Thank you!

**Comment by TheLukeGuy** [comment]
Now emojis aren't working at all :P

**Comment by TheLukeGuy** [comment]
It also throws `Uncaught ReferenceError: $ is not defined
    at emoji.js:5` in the JavaScript console

**Comment by TheLukeGuy** [comment]
Looks like you're trying to call something in jQuery but for some reason the `$` shortcut isn't working...

**Comment by TheLukeGuy** [comment]
Nevermind, I figured it out. Tell people to add `<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>` to their head tag

**Comment by csf30816** [comment]
I was going to say that but I had to leave.
