### ISSUE TITLE
SVG-Emoji2

### ISSUE THREAD

**Issue by csf30816** [TheLukeGuy/thelukeguy.github.io#2]
Hey! Check my profile for SVG Emoji 2. It is not  ready yet. I am just telling you in advanced 👍

**Comment by csf30816** [comment]
You will be notified when it is available :)

**Comment by TheLukeGuy** [comment]
Awesome, thank you for notifying me!

**Comment by csf30816** [comment]
No problem! https://github.com/csf30816/SVG-Emoji2/wiki/Usability for more info

**Comment by csf30816** [comment]
I will be adding :raging: soon

**Comment by TheLukeGuy** [comment]
Yeah, I noticed you hadn't added that.

**Comment by csf30816** [comment]
:)

**Comment by csf30816** [comment]
It should work fine, but notify me of any bugs/issues.

**Comment by TheLukeGuy** [comment]
It works, but why does `;)` not work?

**Comment by csf30816** [comment]
Have not added blinking one yet :(

**Comment by TheLukeGuy** [comment]
ah ok

**Comment by csf30816** [comment]
added winking one today ;)
